services:
  ocr:
    build: .
    container_name: paddleocr-server
    restart: unless-stopped
    ports:
      - "18001:8000"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ocr_models:/root/.paddleocr

volumes:
  ocr_models:
